name: lockout
favicon: null
layout_spectrum: 0.8827248520683497
typography_spectrum: 0.6166490416508168
title: lockout
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.229294573655352
  lightness: 0.3372879442758858
  saturation: 0.22642422374337912
  rhythmicContrast: 0.2635119007900357
purpose: []
